"""add campaigns table

Revision ID: 89ee80a5444f
Revises: 
Create Date: 2025-12-14 14:19:37.960684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ee80a5444f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=False),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('daily_budget', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('google_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('ad_headline', sa.String(length=255), nullable=False),
    sa.Column('ad_description', sa.Text(), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
